import { connect }from 'react-redux'

const LeaderboardPage = (props) => {
    return (
        <div>
            <h1>Leaderboard</h1>
            <table>
                <thead>
                    <tr>
                        <th>Users</th>
                        <th>Answered</th>
                        <th>Created</th>
                    </tr>
                </thead>
                <tbody>
                    {props.users.map((user) => (
                        <tr key={user.id}>
                            <td>
                                <img
                                    src={user.avatarURL}
                                    alt="user-avatar"
                                    className="avatar-table"
                                />
                                <p>{user.name}</p>
                                <h5>{user.id}</h5>
                            </td>
                            <td>{Object.keys(user.answers).length}</td>
                            <td>{user.questions.length}</td>
                        </tr>
                    ))}
                </tbody>
            </table>
        </div>
    )
}

const mapStateToProps = ({ users }) => ({
    users: Object.values(users).sort(
        (a, b) =>
            Object.keys(b.answers).length +
            b.questions.length -
            (Object.keys(a.answers).length + a.questions.length)
        ),
  });
  
export default connect(mapStateToProps)(LeaderboardPage);

// Console: <tr> cannot appear as a child of <table>. 
// Add a <tbody>, <thead> or <tfoot> to your code 
// to match the DOM tree generated by the browser.